source "https://rubygems.org"

gem "metanorma-cli"

# Included with Ruby 3.x, but explicitly needed by Ruby 4.x
gem "benchmark"
gem "ostruct"
gem "tsort"
gem "win32ole", platforms: [ :windows ]
gem "faraday-retry"
gem "sassc-embedded"

# Pick up modified Rouge with "pdf" (COS) and ASN.1 syntax support
# Comment out the following line for ISO flavour, Keep it in for PDFa flavour.
gem "rouge", git: 'https://github.com/petervwyatt/rouge.git', branch: "feature.pdf"

# Prototyping improved layout and appearance for HTML and PDF
# gem "metanorma-taste", git: 'https://github.com/petervwyatt/metanorma-taste.git'
# gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso", branch: "main"
# gem "metanorma-ribose", git: "https://github.com/metanorma/metanorma-ribose", branch: "main"
